name: deployProject
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: PHP VERSION
        run: php -v

      - name: Composer install
        run: composer install
# Test solo en maquina local
# - name: Laravel Test
#   run: php artisan test
