name: deployProject
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: PHP VERSION
        run: php -v

      - name: Composer install
        run: composer install
      - name: clean confi
        run: php artisan config:cache
      # - name: fill DB
      #   run: php artisan migrate --force --seed

      # - name: fresh db
      #   run: php artisan migrate:fresh --seed

      # Test solo en maquina local
      # - name: Laravel Test
      #   run: php artisan test
